language: node_js
node_js:
- 8.9.0
dist: trusty
git:
  depth: false
branches:
  only:
  - develop
  - "/^feature\\/.*$/"
jobs:
  include:
    - stage: "Fundamental Vue build"
      name: "Unit tests"
      script: "npm test"
notifications:
  email:
    on_failure: always
    on_success: change
